// app/layout.jsx
import localFont from "next/font/local";
import { Poppins } from "next/font/google";
import "./globals.css";
import NavbarFooterWrapper from "./components/NavbarFooterWrapper"; // NEW wrapper
import { Toaster } from "react-hot-toast";
// Local fonts
const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  variable: "--font-poppins",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`
          ${geistSans.variable}
          ${geistMono.variable}
          ${poppins.variable}
          antialiased bg-white text-black
        `}
      >
        {/* ✅ Client wrapper handles navbar/footer visibility */}
        <NavbarFooterWrapper>{children}
            <Toaster position="top-right" />
        </NavbarFooterWrapper>
      </body>
    </html>
  );
}
